### ISSUE TITLE
ansible-role-httpd and bertvv.httpd out of sync

### ISSUE THREAD

**Issue by stevestrutt** [bertvv/ansible-role-httpd#7]
Hi bertvv.httpd has not been updated to support Centos 7. The version of httpd.conf.j2 used is for Centos 6 (?)  as it it has 'Include conf.d/*.conf'.  This overwrites the installed version of httpd.conf which has 'include conf.modules.d/*.conf. ls

ansible-role-httpd has been updated to use the latest version of httpd.conf with the include for conf.modules.d/*.conf and runs correctly. However, its meta/main.yml has an unnecessary dependency for bertvv.httpd which pulls in the broken code and again overwrites httpd.conf with the old version, ignoring all the conf files in conf.modules.d.

**Comment by bertvv** [comment]
I just released a new version (v1.3.0) that now is in sync with the code in the Github repository.

Can you check if this work for you now?
